### ISSUE TITLE
When saving additiona spacing always applied

### ISSUE THREAD

**Issue by oreaird** [ahmadalli/vscode-nginx-conf#5] opened 2022-02-28 16:01 UTC
When turning on "nginx-conf-hint.format.align" and then pressing "save" the linter correctly aligns all the values, however, each time after you save, it adds additional spaces between the key-value pairs.

**Comment by ahmadalli** [comment] 2024-03-23 14:12
Closing as duplicate of #7

**Closed by ahmadalli** 2024-03-23 14:12 UTC
